### ISSUE TITLE
Nuki Pro issue with version 0.3.10

### ISSUE THREAD

**Issue by mTnlez** [kvj/hass_nuki_ng#102]
Hey,

I upgrade the version from 0,3.9 to 0.3.10 since then I cannot lock the Nuki from HA.
Using only webapi, (No bridge) 
adding SS of the issue.
![image](https://user-images.githubusercontent.com/109160312/188507696-faf0c790-0b38-416a-8868-42f1b210624b.png)

Hope you could help me,

Thanks,
Matan.

**Comment by Xites** [comment]
Downgrade to 0.3.8 helps.

**Comment by donmatanon** [comment]
Same issue for me. 404 respcode.
tried 0.3.8, 0.3.9, 0.3.10, all seems to have same issue.

**Comment by kvj** [comment]
Please try 0.3.11

**Comment by donmatanon** [comment]
> Please try 0.3.11

Excellent, working!
Thanks for the quick fix.
