### ISSUE TITLE
Impossible to had the repository into HA 2022.11.3

### ISSUE THREAD

**Issue by tfuzeau** [kvj/hass_nuki_ng#118]
Hello,

I'm trying to add the Nuki NG repository into HA 2022.11.3, I have the following error:
https://github.com/kvj/hass_nuki_ng is not a valid add-on repository

I've tried multiple time, without chance, is there any change we can do to solve the issue? Or to install it manually?

Thank you,

Thomas

**Comment by alexdelprete** [comment]
I just tried, and it works fine. Be sure to select `Integration` under the Repo URL field.

![image](https://user-images.githubusercontent.com/7027842/202955839-25251d90-65b4-46e2-a9f5-a3cd663ee6c2.png)

**Comment by tfuzeau** [comment]
Thanks, I've read again the instruction and understand where my mistake was: I tought it was a repository to install into HA directly and not into HACS ( https://hacs.xyz/ ).
I've installed HACS following their instruction and it worked! Sorry for the noise, maybe you could add a quick sentense about HACS and it's needed to be installed to add this repo.

Thank you!

**Comment by alexdelprete** [comment]
> Sorry for the noise, maybe you could add a quick sentense about HACS and it's needed to be installed to add this repo.

It's literally in the first install step, you need to read more carefully:

![image](https://user-images.githubusercontent.com/7027842/203091286-b1b17cf1-87a4-4831-9d49-13848a39de4c.png)
