### ISSUE TITLE
https://github.com/kvj/hass_nuki_ng is not a valid add-on repository

### ISSUE THREAD

**Issue by Rood75** [kvj/hass_nuki_ng#121]
I want to add the repo to my Pi3b HA, but getting an error: https://github.com/kvj/hass_nuki_ng is not a valid add-on repository.

Removing some old repo's and reboot didn't fix the issue.

Anyone a clue?

**Comment by alexdelprete** [comment]
Did you carefully read the instructions?

![image](https://user-images.githubusercontent.com/7027842/204669388-507d4cc8-ce89-425e-8fd7-500606ecef92.png)

Ensure you choose the correct Category.

**Comment by Rood75** [comment]
Thank you for your quick response!

I missed the prereq. HACS and was trying to add the repo as a normal add-on... My bad...
