### ISSUE TITLE
Is there a workaround if you only have Home Assistant available over HTTPS?

### ISSUE THREAD

**Issue by fkroepfl** [kvj/hass_nuki_ng#127]
Since remote access to Home Assistant secured via DuckDNS is almost essential, the question is whether there is a way to work around the limitation that the bridge does not support HTTPS callbacks?

Or do one simply have to live without the NUKI LOCK integration?

BR

**Comment by alexdelprete** [comment]
Remote access to HA can be secured in several ways, not only DuckDNS, but that's a topic that has nothing to do with the integration.

The Nuki Bridge does not support https, so HA has to be available locally through HTTP. This can be achieved using the NGINX Proxy addon (https only externally and http/https on the LAN), and this has already been discussed in other issues, see here: https://github.com/kvj/hass_nuki_ng/issues/109#issuecomment-1258676343.

**Comment by fkroepfl** [comment]
Thanks for the tip, which I will be happy to follow up on. 😀
Have a nice day. 🤗
