### ISSUE TITLE
It never shows „charging“

### ISSUE THREAD

**Issue by superpower10** [kvj/hass_nuki_ng#133]
I connected the Nuki 3.0 Pro over Web API **_and_** Bridge API. 

If I put in the original charging cable the light at the bottom of the lock starts blinking till battery is 100% charged.

But the integration never shows that the lock is charging. It always says „not charging“

Everything is on the newest Version (HACS, Home Assistant, Nuki HACS integration, etc.)

**Comment by phantomsphorever** [comment]
Same for me, but it looks like this integration has been abandoned by the author?

**Comment by superpower10** [comment]
Yesterday it showed it. Why, I don’t know.
