### ISSUE TITLE
2024.1 log WARNING

### ISSUE THREAD

**Issue by neildsb** [kvj/hass_nuki_ng#173]
Core
2024.1.0
Supervisor
2023.12.0
Operating System
11.2
Frontend
20240103.3

Logger: homeassistant.components.lock
Source: helpers/deprecation.py:204
Integration: Lock (documentation, issues)
First occurred: 10:00:39 pm (2 occurrences)
Last logged: 10:00:39 pm

SUPPORT_OPEN was used from nuki_ng, this is a deprecated constant which will be removed in HA Core 2025.1. Use LockEntityFeature.OPEN instead, please create a bug report at https://github.com/kvj/hass_nuki_ng/issues

**Comment by dhoeben** [comment]
I too have this issue.

**Comment by inc-ali** [comment]
Solved in #176
