### ISSUE TITLE
HA Core 2025.1 Deprecated Constant Changes Required

### ISSUE THREAD

**Issue by craibo** [kvj/hass_nuki_ng#179]
Logger: homeassistant.components.lock
Source: helpers/deprecation.py:205
Integration: Lock (documentation, issues)
First occurred: 11:13:11 (2 occurrences)
Last logged: 11:13:11

SUPPORT_OPEN was used from nuki_ng, this is a deprecated constant which will be removed in HA Core 2025.1. Use LockEntityFeature.OPEN instead, please create a bug report at https://github.com/kvj/hass_nuki_ng/issues

**Comment by neildsb** [comment]
duplicate https://github.com/kvj/hass_nuki_ng/issues/173
