### ISSUE TITLE
Add logo and icon for dark background

### ISSUE THREAD

**Issue by kongo09** [kvj/hass_nuki_ng#20]
Currently, the integration uses the original Nuki logo as logo and icon:
https://github.com/home-assistant/brands/tree/master/custom_integrations/nuki_ng

It is difficult to see this in dark themes:
![image](https://user-images.githubusercontent.com/640121/145682046-e0d28a3e-9f94-4433-8538-27a309b579b6.png)

HA allows to provide images optimized for dark background:
https://github.com/home-assistant/brands#image-specification

I propose to find/design and add these.

**Comment by kongo09** [comment]
Nuki itself is using this icon for its Android app:

![image](https://user-images.githubusercontent.com/640121/145682139-c03af7d5-7b31-41e0-bfdc-ae0eb5d79348.png)

Source: https://play.google.com/store/apps/details?id=io.nuki

**Comment by kongo09** [comment]
To facilitate the discussion, I've prepared the relevant variants of the icon

|  256 x 256           |   dark  |  white  |
|-------------------|---------|---------|
| not transparent  | ![bl_nuki](https://user-images.githubusercontent.com/640121/145682823-32df6366-5e90-4ad2-93fc-eb0d94e2dd91.png) | ![nuki](https://user-images.githubusercontent.com/640121/145682855-8f607711-3398-4c05-9e79-f1b81fe03d2f.png) |
| transparent        | ![tr_bl_nuki](https://user-images.githubusercontent.com/640121/145682875-523e1ec8-d089-49cb-a7a5-dbd40cd500b1.png) | ![tr_nuki](https://user-images.githubusercontent.com/640121/145682888-963d3859-c124-4df6-b010-bd8dc152ed2f.png) |

Plus the same in high resolution 512 x 512

![bl_nuki@2x](https://user-images.githubusercontent.com/640121/145682972-deff696b-2c06-4cef-b6b3-83be731622e6.png)

![nuki@2x](https://user-images.githubusercontent.com/640121/145682981-12a92a8d-f39b-4c93-9973-868cd9ed5e8b.png)

![tr_bl_nuki@2x](https://user-images.githubusercontent.com/640121/145682997-e0208a23-112b-40b3-b9e4-ad3bb1de37ce.png)

![tr_nuki@2x](https://user-images.githubusercontent.com/640121/145683006-8ef5b7e5-2a7a-4a2d-8f8c-843c9ae94046.png)

**Comment by kongo09** [comment]
Personally, I would opt for the non-transparent white version for both, dark and light themes. That would be consistent with the Nuki app and due to the contrast it is visible in both themes.

@alexdelprete What do you think? Didn't you do the first version that's uploaded?

**Comment by alexdelprete** [comment]
> What do you think? Didn't you do the first version that's uploaded?

I simply duplicated the official integration folder.

Frankly, I don't like that circle, I prefer the Nuki logo as it is, but I agree it's not much visible, maybe we can work on making it more visible? But I prefer the Nuki with letters and the yellow dot. But that's just my personal preference. :)

**Comment by kongo09** [comment]
As you guys prefer the logo also for the icons, I've submitted dark theme variants for the logos, but not for the circle icons.

https://github.com/home-assistant/brands/pull/3072
