### ISSUE TITLE
Invalid repository @ HACS

### ISSUE THREAD

**Issue by rockas69** [kvj/hass_nuki_ng#24]
Got invalid repository when trying to add it to HACS

**Comment by alexdelprete** [comment]
Repo is working fine. What url are you using?

**Comment by rockas69** [comment]
![image](https://user-images.githubusercontent.com/58712323/146925944-84eadabe-e12f-4427-b3b3-fd1150c2a238.png)

**Comment by alexdelprete** [comment]
You have to choose category "integration":

![image](https://user-images.githubusercontent.com/7027842/146939424-29f1be86-59b3-4f14-92f1-a36b532268cf.png)

**Comment by Inferi0r** [comment]
> ![image](https://user-images.githubusercontent.com/58712323/146925944-84eadabe-e12f-4427-b3b3-fd1150c2a238.png)

You are adding this repo to the HA official add-on store, however you should add it as custom repo within HACS!

I see this mistake happens often to many users.

**Comment by alexdelprete** [comment]
First lines of the instructions:

![image](https://user-images.githubusercontent.com/7027842/147168115-d70caa82-176c-401c-9e9b-fefa05e25961.png)

**Comment by rockas69** [comment]
thank you so much, sorted out!

**Comment by alexdelprete** [comment]
> thank you so much, sorted out!

glad you did. could you close the issue please? button right under this post. thank you. :)

**Comment by kvj** [comment]
Closing, as the issue has been resolved
