### ISSUE TITLE
Entity for Doorbell

### ISSUE THREAD

**Issue by 0znn** [kvj/hass_nuki_ng#25]
Hello, 

thanks for the great Integration for the Nuki System. 

Do u know, how to add, a Trigger in Homassistant for a doorbell? That i can automate some things, if the doorbell rings? 

that will be great. 

Greetings

**Comment by alexdelprete** [comment]
Hi,

why do you open an issue for a doorbell trigger in this integration? :)

**Comment by jjuuzzii** [comment]
I want to know this too.

**Comment by kvj** [comment]
Please be more specific and we could help. 

Which entities your doorbell integration is exposing in Home Assistant?

**Comment by jjuuzzii** [comment]
The openerner gets the Signal Form the Doorbell Button. 
hass should Grab this „Signal“ and Turn it Into a binarem Sensor. 

`{{ trigger.json.ringactionState }}`
this is the trigger

**Comment by kvj** [comment]
> edit: the binary_sensor already exists

So, you have everything you need already, right?

**Comment by jjuuzzii** [comment]
I do yes. @0znn  Schlupf also i think..

**Comment by 0znn** [comment]
hmm. sorry for the long time ago.  The sensor doesn´t show the information that i want. 

I want to trigger something, if someone the doorbell rings. The sensor show only if the Ring to open feature is active or not. 

Maybe i am stupid. 

Greetings.

**Comment by alexdelprete** [comment]
> I want to trigger something, if someone the doorbell rings

Check this post: https://community.home-assistant.io/t/nuki-card-with-callback-support-supports-both-lock-opener-it-replaces-the-official-integration/311932/1345?u=alexdelprete
