### ISSUE TITLE
Cannot set up integration as I use a different port than 8080.

### ISSUE THREAD

**Issue by deam0n** [kvj/hass_nuki_ng#32]
Hi,
When I try to set up this integration, I got the error:

Failed to get list of devices from bridge: Failed to parse: http://192.168.178.22:9090:8080/list?token=XXXXXXXX

In fact I've set up my NUKI API on the port 9090 as the 8080 is already used for something else in the network.

Is it possible to have an input for the port to be used in the integration set up?

**Comment by kvj** [comment]
oh, thanks for the report. sure, I will fix it

**Comment by kvj** [comment]
Please update to 0.2.1. The issue should be fixed

**Comment by deam0n** [comment]
Thanks,

Now I get the error:

Bridge doesn't support HTTPS callbacks. Please make your Home Assistant accessible via HTTP.

Is this a limitation? I've the official Nuki integration working (I do not remember if I had to provide the callback), but My HA instance is only available via https.

**Comment by kvj** [comment]
If you have a hardware bridge (black cube) then yes, the bridge doesn't support HTTPS callbacks. No real-time status updates will be possible. The original Nuki integration doesn't use callbacks at all, only polling.

I was a bit confused by your original message, I've mentioned that the port is being used by something else. How that is possible, as Bridge has basically only one port open?

**Comment by deam0n** [comment]
Indeed! (facepalm)
I guess I've just changed it as a security freak that I try to be. (never leave default ports, if you can change it)
Humm, now I'm battling myself on having HA on http (and support https via rpm) so I can use your amazing integration! heheh

**Comment by kvj** [comment]
Yeah, it's up to you. 
You can quickly set up Nginx proxy, for example, and expose only hooks endpoints via HTTP

**Comment by deam0n** [comment]
OK, I've changed my instance to be available over http..
but now I get the following error:

Failed to get list of devices from bridge: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //192.168.178.22:9090/list?token=XXXXXXXXX (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff603833a0>: Failed to establish a new connection: [Errno -3] Try again'))

no matter if I restart the bridge, or wait some time, I'll have this error

**Comment by kvj** [comment]
That looks strange. Please make sure you only enter `192.168.178.22:9090` as a field value, and not a full URL

**Comment by deam0n** [comment]
indeed that fixed it!

Thanks a lot!
