### ISSUE TITLE
Configuration.yaml

### ISSUE THREAD

**Issue by giuliandenicola1** [kvj/hass_nuki_ng#39]
Hi, is it possible to have this integrated via YAML instead of UI? If so, how?

**Comment by kvj** [comment]
Hi,

The configuration via the UI is the recommended approach by the HASS development guide. There are no such plans

**Comment by giuliandenicola1** [comment]
Ah that's unfortunate! When something changes for some reason (e.g. door/name, IP address, Api) or if you want to change the polling interval then you have to delete the integration and fill everything in again. Same goes for changing home assistant instances. 

I just remembered right now, I could also do this inside the `config/.storage/core_entries` file.

**Comment by kvj** [comment]
@giuliandenicola1 Re-configuration via the UI is a different story. That is possible to implement
