### ISSUE TITLE
Bridge Callback Set after upgrade to integration newest ver always is off

### ISSUE THREAD

**Issue by KitHubek** [kvj/hass_nuki_ng#55]
Bridge Callback Set after install itegration u[grade is always off. After update always was ON. Integration working and is possible open lock via HA and all seems to worling ok.

![callbacksetoff](https://user-images.githubusercontent.com/91805313/163684868-d895ac75-3c0a-4f33-9db9-5d6cfc9a661c.jpg)

**Comment by kvj** [comment]
Please update to 0.3.4. Should be fixed now

**Comment by KitHubek** [comment]
updated to 0.3.4 and problem fixed. big thanks for quick action, have a nice day
