### ISSUE TITLE
Feature Request: Who last opened the door?

### ISSUE THREAD

**Issue by danieljgmaclean** [kvj/hass_nuki_ng#59]
I know that Nuki supports providing access to others to open the lock, but i'm curious if there is a way to know who last opened the door or who or what device actually opened the door.

**Comment by noxhirsch** [comment]
This data can be polled from the cloud (https://api.nuki.io/smartlock/log?limit=1). It maybe could be implemented so that the integration retrieves the log from the cloud e.g. 5 seconds after the last change of the lock (to give the cloud server some time to get updated).

**Comment by kvj** [comment]
Added in 0.3.8

**Comment by jesjimher** [comment]
Just upgraded to 0.3.11 from (I think) 0.3.4, but I can't see this new "last user" entity. Integration shows in HACS as correctly upgraded to 0.3.11, and I've restarted HA several times. Am I missing something, or it may have been some regression since 0.3.8?

Thanks!
