### ISSUE TITLE
Add DoorSensorState 0 to enum

### ISSUE THREAD

**Issue by b3nn0** [kvj/hass_nuki_ng#62]
Hi,
I have a Nuki Lock v3, but no other Nuki sensors.
Apparently, it delivers a DoorSensorState of 0, resulting in an exception in this integration.
It also makes the lock entity not work correctly (i.e. never updates).

Adding the DoorSensorState UNAVAILABLE = 0 to states.py solves all issues.
Could this be added for the next version?

```
class DoorSensorStates(BaseStates):
    UNAVAILABLE = 0
    ...
```

**Comment by alexdelprete** [comment]
Strange, the [bridge API doc](https://developer.nuki.io/page/nuki-bridge-http-api-1-13/4#heading--doorsensor-states) doesn't mention 0 as a possible state:

![image](https://user-images.githubusercontent.com/7027842/175769331-dd3ef47f-fd36-4b52-a3a1-ef1812191cf2.png)

**Comment by b3nn0** [comment]
Yup.. got the idea from here:
https://github.com/dauden1184/RaspiNukiBridge/issues/2
only seems to affect the Nuki V3 lock.

Works perfectly ever since adding that though.

**Comment by alexdelprete** [comment]
They should update the docs...
