### ISSUE TITLE
'nuki lock' not showing up

### ISSUE THREAD

**Issue by asetGem** [kvj/hass_nuki_ng#73]
Hi, I downloaded the HACS integration as described.
Then, I restarted home assistant, and went to the `integrations` section.
Here, I can find the `Nuki` integration, but not `Nuki lock`. How can I find it?
Thanks

**Comment by matthijskeij** [comment]
I have exactly the same issue.
HACS 1.25.5
Nuki Lock 0.3.5
HA core-2022.6.7

**Comment by Ir0nhid3** [comment]
Same here

**Comment by matthijskeij** [comment]
I have exactly the same issue.
HACS 1.25.5
Nuki Lock 0.3.5
HA core-2022.6.7

**Comment by MattieGit** [comment]
Solved for me. I thought I had done a hard refresh already, but probably not.
Anyway, a hard refresh (Cmd - Shift - R on Mac for Chrome browser) clears the cache and then "Nuki Lock" shows up in the list of integrations.

**Comment by Ir0nhid3** [comment]
> Solved for me. I thought I had done a hard refresh already, but probably not. Anyway, a hard refresh (Cmd - Shift - R on Mac for Chrome browser) clears the cache and then "Nuki Lock" shows up in the list of integrations.

I tried it a few times now and you are correct - that solved my issue too.

**Comment by asetGem** [comment]
The hard refresh did not work for me. I uninstalled both nuki and HACS, reinstalled, and now it works :)
