### ISSUE TITLE
Unlatch?

### ISSUE THREAD

**Issue by Fidaninho** [kvj/hass_nuki_ng#8]
Hello,
is there no option to unlatch?
This is by far the most important feature. Otherwise you are dependend from Nuki App to get it.

**Comment by kvj** [comment]
Yes, there is. I also use Nuki lock with unlatch function.

Unfortunately, lovelace UI doesn't show the "Open/unlatch" button in UI, but you can call `lock.open` service to unlatch.

**Comment by Fidaninho** [comment]
Thank you very much. I found it
    	
    
  

 Von: Konstantin ***@***.***>Gesendet: Montag, Dezember 6, 2021 9:06 AMAn: kvj/hass_nuki_ngCc: Fidaninho; State changeBetreff: Re: [kvj/hass_nuki_ng] Unlatch? (Issue #8) 
Yes, there is. I also use Nuki lock with unlatch function.
Unfortunately, lovelace UI doesn't show the "Open/unlatch" button in UI, but you can call lock.open service to unlatch.
