### ISSUE TITLE
Error communicating with Nuki bridge

### ISSUE THREAD

**Issue by sp7dpt** [kvj/hass_nuki_ng#83]
I removed the Nuki Lock integration and wanted to re-add after updating to 0.3.7. It cannot be added again. I have an error "Error communicating with Nuki bridge". I am entering a valid IP address and token.
Home Assistan Nuki native integration works fine and connects.
What's the problem?
![nuki](https://user-images.githubusercontent.com/54576080/186633040-dd9792a8-2c33-4139-8c8a-7e6e5d17c317.JPG)

**Comment by sp7dpt** [comment]
When I only add a bridge api token I have such an error:
![nuki token](https://user-images.githubusercontent.com/54576080/186640871-79edc4d6-bd8f-43f6-8dc7-e040d13b7ccc.JPG)

When I only add a web api token I have such an error:
![nuki api](https://user-images.githubusercontent.com/54576080/186641074-66250a43-8ef2-4008-bc9a-e12d224d2cc1.JPG)

**Comment by sp7dpt** [comment]
I brought back an older version of Nuki Lock and it connects correctly.

**Comment by kvj** [comment]
ah, yes. that's a bug. thanks for reporting
