### ISSUE TITLE
Failed to get list of devices from web API: 0

### ISSUE THREAD

**Issue by donmatanon** [kvj/hass_nuki_ng#88]
Nuki 3 pro, no bridge. 
trying to set it up with API key

getting the following: 

Logger: custom_components.nuki_ng.config_flow
Source: custom_components/nuki_ng/config_flow.py:51
Integration: Nuki Lock ([documentation](https://github.com/kvj/hass_nuki_ng), [issues](https://github.com/kvj/hass_nuki_ng/issues))
First occurred: 1:10:58 PM (2 occurrences)
Last logged: 1:11:06 PM

Failed to get list of devices from web API: 0
Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/config_flow.py", line 51, in find_nuki_devices
    title = response[0]["name"]
KeyError: 0

API key is set correctly with all rights.
Any suggestions?
Thanks.

**Comment by kvj** [comment]
yes. upgrade to the latest version 0.3.8

**Comment by donmatanon** [comment]
i am on 0.3.8 :(

**Comment by kvj** [comment]
Yeah, more changes == more bugs.

Please update to 0.3.9. Should be fixed

**Comment by donmatanon** [comment]
> Yeah, more changes == more bugs.
> 
> Please update to 0.3.9. Should be fixed

Works like a charm!
Awesome stuff man, appreciate that.
