### ISSUE TITLE
How to use it when u have https?

### ISSUE THREAD

**Issue by malosaa** [kvj/hass_nuki_ng#94]
Well my system has duckdns to access hass..
I can't access trough http:// getting error server response.. so not accessible..

How can i solve this issue ? 
Because cant use this integration now.

I also have adguard active.

regards

**Comment by kvj** [comment]
Nuki bridge is a local device, designed to be accessible via from local network.
If your hass server and Nuki bridge aren't able to access each other via http, then you won't be able to setup this.
In this case you can still use this integration in web API only mode, just leave both bridge URL and bridge token empty and input your web API token. This this case the integration will use internet to poll device data

**Comment by malosaa** [comment]
Many thanks for the reply, 
it works like you said, but it takes long to update, is there a way to setup the poll rate ? 

regards

**Comment by kvj** [comment]
poll rate in seconds is a part of the integration configuration dialog. default value is 30 seconds

**Comment by malosaa** [comment]
thanks, i already figured it out, i have installed ngix and adguard, so i now run https and http, now the addon works as expected :) 

thank you
